[project]
name = "sd-turbo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yuanpa", email = "juanpazorro2007@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.15.0",
    "diffusers>=0.41.0",
    "torch>=2.14.1",
    "transformers>=5.19.0",
]

[project.scripts]
sd-turbo = "sd_turbo:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
